version: '3.5'
services:
  medondo-backend:
    container_name: medondo-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3000
    # environment:
