version: '3.5'
services:
  medondo-backend:
    container_name: medondo-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      NODE_CERT: "false"
