export enum Event {
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED",

  ADD_CHANNEL = "ADD_CHANNEL",
  JOIN_CHANNEL = "JOIN_CHANNEL",
  LEAVE_CHANNEL = "JOIN_CHANNEL",

  ADD_MENTION = "MENTION",
  MENTIONS = "MENTION",

  AUTH = "AUTH",
  ADD_USER = "ADD_USER",
  EDIT_USER = "EDIT_USER",

  SEND_MESSAGE = "SEND_MESSAGE",
  SEND_DIRECT = "SEND_DIRECT",

  USERS = "USERS",
  CHANNELS = "CHANNELS",
  DIRECTS = "DIRECTS",

  TYPING = "TYPING",
  STOPPED_TYPING = "STOPPED_TYPING",
}
